{{- /*
Generates PRIMARY/REPLICAS Secret for nebula-sync.
If nebulaSync.password is empty:
  - If nebulaSync.allowEmptyPassword=true -> use trailing pipe "http://host:port|"
  - Else -> hard fail (require password)
*/ -}}
{{- $neb := .Values.nebulaSync | default (dict) -}}
{{- if and ($neb.enabled | default true) (not $neb.existingSecret) -}}
{{- $fullname := include "pihole.fullname" . -}}
{{- $ns := .Release.Namespace -}}
{{- $replicas := int (default 1 .Values.replicaCount) -}}
{{- $port := default 80 (get (get $neb "primary" | default (dict)) "port") -}}
{{- $pwd := default "" $neb.password -}}
{{- $allowEmpty := default false $neb.allowEmptyPassword -}}
{{- if and (eq $pwd "") (not $allowEmpty) -}}
  {{- fail "nebulaSync.password is required when generating the nebula-sync Secret (or set nebulaSync.allowEmptyPassword=true to permit empty password)" -}}
{{- end -}}
{{- $suffix := "|" -}}
{{- if ne $pwd "" -}}
  {{- $suffix = printf "|%s" $pwd -}}
{{- end -}}

{{- $primaryHost := printf "%s-0.%s-hl.%s.svc.cluster.local:%v" $fullname $fullname $ns $port -}}
{{- $primaryURL := printf "http://%s%s" $primaryHost $suffix -}}

{{- $replicaURLs := list -}}
{{- range $i, $e := until $replicas }}
  {{- if gt $e 0 }}
    {{- $host := printf "%s-%d.%s-hl.%s.svc.cluster.local:%v" $fullname $e $fullname $ns $port -}}
    {{- $replicaURLs = append $replicaURLs (printf "http://%s%s" $host $suffix) -}}
  {{- end }}
{{- end -}}
{{- $replicasCSV := join "," $replicaURLs -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-nebula-sync" $fullname }}
  labels:
    app.kubernetes.io/name: nebula-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  primary: {{ $primaryURL | b64enc }}
  replicas: {{ $replicasCSV | b64enc }}
{{- end }}
