{{- if and .Values.clustering.enabled (gt (int .Values.replicaCount) 1) }}
{{- $fullname := include "technitium-dns.fullname" . }}
{{- $labels := include "technitium-dns.labels" . }}
{{- $selectorLabels := include "technitium-dns.selectorLabels" . }}
{{- range $i := until (int $.Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-node-{{ $i }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: web-http
      port: {{ $.Values.webConsole.httpPort }}
      targetPort: web-http
      protocol: TCP
    {{- if or $.Values.webConsole.enableHttps $.Values.clustering.enabled }}
    - name: web-https
      port: {{ $.Values.webConsole.httpsPort }}
      targetPort: web-https
      protocol: TCP
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
{{- end }}
{{- end }}
