apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium-dns.fullname" . }}-headless
  labels:
    {{- include "technitium-dns.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
  selector:
    {{- include "technitium-dns.selectorLabels" . | nindent 4 }}
