apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium-dns.fullname" . }}-headless
  labels:
    {{- include "technitium-dns.labels" . | nindent 4 }}
spec:
  clusterIP: None
  {{- if .Values.clustering.enabled }}
  publishNotReadyAddresses: true
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: web-http
      port: {{ .Values.webConsole.httpPort }}
      targetPort: web-http
      protocol: TCP
    {{- if or .Values.webConsole.enableHttps .Values.clustering.enabled }}
    - name: web-https
      port: {{ .Values.webConsole.httpsPort }}
      targetPort: web-https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "technitium-dns.selectorLabels" . | nindent 4 }}
